apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meu-app
  template:
    metadata:
      labels:
        app: meu-app
    spec:
      serviceAccountName: meu-app-sa
      containers:
        
      - name: meu-app
        # Imagem v3 com Python + Flask + Psycopg2
        image: southamerica-east1-docker.pkg.dev/gsre-489913/meu-repo/meu-app:v3
        ports:
        - containerPort: 80
        
        # DEFINIÇÃO DE RECURSOS (Essencial para o Autoscaling)
        resources:
          requests:
            cpu: "100m"     # Reserva 0.1 núcleo (garante que o pod tenha fôlego)
            memory: "128Mi"
          limits:
            cpu: "200m"     # Teto de 0.2 núcleo para forçar a escala mais rápido no teste
            memory: "256Mi"

        env:
        # Endereço IP Privado da instância do Cloud SQL
        - name: DB_HOST
          #value: "34.39.128.208"
          value: "10.36.0.5 "
        
        # Nome do banco de dados que criamos no Cloud SQL Studio
        - name: DB_NAME
          value: "billing_db"
        
        # Usuário criado via gcloud
        - name: DB_USER
          value: "app-user"
        
        # SENHA PROTEGIDA: O valor não está aqui, mas sim no Kubernetes Secret
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-pass-k8s
              key: password

---
apiVersion: v1
kind: Service
metadata:
  name: meu-app-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: meu-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80